apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-ns1
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: aozcalisan/webapp2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-ns1  
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: app-ns1    
type: Opaque
stringData:
  db_server: db.example2.com
  db_username: admin2
  db_password: P@ssw0rd2!